create table public.detection_reports (
  id integer generated by default as identity primary key,
  farmer_id varchar(64) not null default 'premium-farmer-001',
  crop varchar(80) not null,
  disease varchar(120) not null,
  confidence double precision not null,
  severity varchar(40) not null,
  treatment text not null,
  status varchar(40) not null default 'Reviewed',
  latitude double precision,
  longitude double precision,
  location_name varchar(120),
  image_path varchar(255),
  image_url varchar(255),
  geom extensions.geography(Point, 4326),
  created_at timestamptz not null default now()
);

comment on table public.detection_reports is 'Crop disease detection history for the Vani farmer dashboard.';

create index detection_reports_created_at_idx
  on public.detection_reports (created_at desc, id desc);

create index detection_reports_farmer_id_idx
  on public.detection_reports (farmer_id);

create index detection_reports_geom_idx
  on public.detection_reports using gist (geom);

-- The FastAPI backend connects directly with Postgres credentials and bypasses
-- RLS. Policies are intentionally omitted so the public PostgREST API exposes
-- nothing; add policies here if the frontend ever queries Supabase directly.
alter table public.detection_reports enable row level security;
